### ISSUE TITLE
[ not working ] 

### ISSUE THREAD

**Issue by ThisMe124** [iamdeepak92/threads-scraper#1]
I am test on replit not working. On endpoints userid/:username

And response like this:
![Screenshot_20230709-181053](https://github.com/iamdeepak92/threads-scraper/assets/88891071/bd06b9ff-2b10-44c2-a6b4-75859bd92f12)

I changed it without directly parsing the html response like this:
![Screenshot_20230709-181143](https://github.com/iamdeepak92/threads-scraper/assets/88891071/a340f645-154a-41b3-83c8-d8f812a724ab)

**Comment by iamdeepak92** [comment]
Replit uses the datacenter ip. Instagram generally blocked the such ip and redirected to login page. Try it your machine it should work.

**Comment by ThisMe124** [comment]
> Replit uses the datacenter ip. Instagram generally blocked the such ip and redirected to login page. Try it your machine it should work.

I am test another, on pterodactly but still same

**Comment by iamdeepak92** [comment]
Threads/Instagram or Facebook blocks datacenter IP on any cloud platform. Better you can test in it on your local machine.
